name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: make lint

      - name: Test
        run: make test
